# Generated by Django 4.1.3 on 2022-11-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
