# Generated by Django 4.1.3 on 2022-11-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_alter_post_descripcion_alter_post_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tags',
            new_name='tag',
        ),
    ]
