# Generated by Django 4.1.3 on 2022-11-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_post_options_alter_tags_options_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
