# Generated by Django 4.1.3 on 2022-11-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_alter_post_id_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['tag'], 'verbose_name_plural': 'Tags'},
        ),
    ]
