# Generated by Django 4.1.3 on 2022-11-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_remove_tags_id_post_tags_id_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['nombre'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='tags',
            name='id_post',
            field=models.ManyToManyField(blank=True, default=1, null=True, to='AppBlog.post'),
        ),
    ]
