# Generated by Django 4.1.3 on 2022-11-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0011_alter_tags_id_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id_post'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
