# Generated by Django 4.1.3 on 2022-11-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0012_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscriptor',
            name='id',
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='id_suscriptor',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
