# Generated by Django 4.1.3 on 2022-11-19 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_remove_suscriptor_id_suscriptor_id_suscriptor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['id_tag'], 'verbose_name_plural': 'Tags'},
        ),
    ]
