# Generated by Django 4.1.3 on 2022-11-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_alter_tags_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id_post',
            field=models.ManyToManyField(default=1, related_name='post_tags', to='AppBlog.post'),
        ),
    ]
